package communication;

public class RemoteObjectReference implements java.io.Serializable{
	/**
	 * autogenerated UID
	 */
	private static final long serialVersionUID = 4532216813002720501L;
	
	String hostIP;
	int hostPort;
	String bindname; // this will be matched with "HostMachineIP:Port/bindname"
	String interfaceImplemented;
	
}
